### ISSUE TITLE
readgroup stats

### ISSUE THREAD

**Issue by MichelMoser** [tobiasrausch/bamStats#1]
Hi i am looking for a lightwheigt tool to get stats from bam files with multiple readgroups. 
I thought you implemented this feature in bamStat. 

But when i run bamStat, it complains about: 

Only one sample (@RG:SM) is allowed per input BAM file RNA2013.07080910.IL2-1ax.bam

Is this feature still in progress? 
Thanks, 
michel

**Comment by tobiasrausch** [comment]
bamStats indeed supports multiple RG groups for the same sample (e.g. multiple libraries). I haven't looked into supporting multiple samples (different SM tags) yet because that appeared to me as fairly uncommon. You can of course always split such a multi-sample BAM file into single sample BAM files using samtools.
